# Generated by Django 3.1.5 on 2021-07-19 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0005_auto_20170808_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcmdevice',
            name='user',
        ),
    ]
