# Generated by Django 3.1.5 on 2021-07-19 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_points'),
        ('fcm_django', '0006_remove_fcmdevice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmdevice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
