# Generated by Django 3.1.5 on 2021-07-19 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('fcm_django', '0007_fcmdevice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmdevice',
            name='app_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de versión'),
        ),
        migrations.AddField(
            model_name='fcmdevice',
            name='app_version',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de versión'),
        ),
        migrations.AddField(
            model_name='fcmdevice',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='countries.country', verbose_name='País'),
        ),
        migrations.AddField(
            model_name='fcmdevice',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fcmdevice',
            name='installation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fcmdevice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fcmdevice',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fcmdevice',
            name='model',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fcmdevice',
            name='os_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fcmdevice',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='fcmdevice',
            name='platform',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fcmdevice',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
